### PR TITLE
Added missing classes for item options in cart.

### PR DESCRIPTION
**Pull request by seb86**

### CODE REVIEW

**Comment by franticpsyx** [comment]
@seb86 are these "missing" in the sense they existed in v1?

**Comment by franticpsyx** [comment]
NM, looks like you are referring to the product template 👍

**Comment by franticpsyx** [comment]
I don't think there's a `value` key there so adding this in would likely trigger a warning -- looks like a mild inconsistency between product/cart templates that we can/should fix in a BW compatible manner. Closing.

**Comment by seb86** [comment]
I did not see an error when I tested this change. Appears to be fine unless you can confirm otherwise. You also have `$option[ 'value' ]` used on [line #26](https://github.com/seb86/woocommerce-subscribe-to-all-the-things/blob/5579d71ee7f5259eb8b308a2ee7bfa417c019f1b/templates/cart/cart-item-subscription-options.php#L26) for the input. `value="<?php echo esc_attr( $option[ 'value' ] ); ?>"`

**Comment by franticpsyx** [comment]
Pulled and checked again, this looks in order.

**Pull request merged**
