### PR TITLE
Add synchronization support to product/cart schemes

### LINKED ISSUE #225: WCS Features Parity Milestone 2: Synchronization
From https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap

### PR DESCRIPTION
**Pull request by franticpsyx**
closes #225

### CODE REVIEW

**Comment by franticpsyx** [comment]
@thenbrent going to merge this one as I don't think I've missed something (famous last words), but if you would like to do a code review yourself or assign it to someone, I'd be grateful.

**Comment by thenbrent** [comment]
@franticpsyx only issue is the `ame_subscription_billing_period_range_data()` method. Was that meant to be named `rename_subscription_billing_period_range_data()` or perhaps just `subscription_billing_period_range_data()`?

Otherwise, LGTM. Amazing work. 💯

**Comment by franticpsyx** [comment]
> Was that meant to be named `rename_subscription_billing_period_range_data()`

Eyes as sharp as an 🦅 's!

**Comment by thenbrent** [comment]
Only on other people’s code 😆

**Pull request merged**
